package com.gt7.bridge.mobile;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 static final String PREF="gt7_revolution_v157",DEF_BRIDGE="http://192.168.1.70:8787"; Handler h=new Handler(Looper.getMainLooper()); LinearLayout root,content,grid; TextView status,clock,gear,speed,best,last,total,max,fuel,aut,weather,wet,brandV,carV,carIdV,trackV,trackIdV; Tach tach; Map<String,String> f=new HashMap<>(),lastGood=new HashMap<>(); Map<String,TextView> vals=new HashMap<>(); Map<String,CheckBox> checks=new HashMap<>(); ArrayList<Long> laps=new ArrayList<>(); String bridge=DEF_BRIDGE,brand="Ferrari",car="F40 '92",track="Sardegna - Road Track - A",lastLapText=""; float maxSpeed=0,fuelStart=Float.NaN,fuelLast=Float.NaN,fuelPerLap=Float.NaN; long lastPacket=0; boolean active=false;
 Runnable poll=new Runnable(){public void run(){pollBridge();h.postDelayed(this,700);}};
 public void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);load();build();h.post(poll);} public void onDestroy(){h.removeCallbacks(poll);super.onDestroy();}
 void load(){SharedPreferences s=getSharedPreferences(PREF,0);bridge=s.getString("bridge",DEF_BRIDGE);brand=s.getString("brand",brand);car=s.getString("car",car);track=s.getString("track",track);active=s.getBoolean("active",false);} int green(){return Color.rgb(57,255,20);} int blue(){return Color.rgb(39,183,255);} int red(){return Color.rgb(255,50,64);} int yellow(){return Color.rgb(255,207,27);} int txt(){return Color.rgb(240,245,250);} int bg(){return Color.rgb(2,7,12);} int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int sp,int c,int style){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);t.setTypeface(Typeface.DEFAULT,style);return t;}
 GradientDrawable box(int stroke,int color,int fill,int rad){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(rad));g.setStroke(dp(stroke),color);return g;} LinearLayout vbox(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
 void build(){FrameLayout frame=new FrameLayout(this);frame.setBackgroundColor(bg());ScrollView scroll=new ScrollView(this);root=vbox();root.setPadding(dp(12),dp(8),dp(12),dp(82));scroll.addView(root);frame.addView(scroll);setContentView(frame);top();content=root;dashboard();bottom(frame);}
 void top(){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(0,0,0,dp(10));TextView menu=tv("☰",28,Color.WHITE,Typeface.NORMAL);TextView title=tv("REVOLUTION GT7",23,Color.WHITE,Typeface.BOLD_ITALIC);status=tv("● CONECTADO",14,green(),Typeface.BOLD);TextView cog=tv("⚙",28,Color.WHITE,Typeface.NORMAL);LinearLayout mid=vbox();mid.setGravity(Gravity.CENTER);mid.addView(title);mid.addView(status);bar.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(56)));bar.addView(mid,new LinearLayout.LayoutParams(0,-2,1));bar.addView(cog,new LinearLayout.LayoutParams(dp(48),dp(56)));cog.setOnClickListener(new View.OnClickListener(){public void onClick(View v){settings();}});root.addView(bar);} 
 void dashboard(){root.removeViews(1,root.getChildCount()-1);mainGauge();grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);root.addView(grid);row(card("MELHOR VOLTA","best",green(),"◷"),card("ÚLTIMA VOLTA","last",blue(),"◷"));row(card("COMBUSTÍVEL","fuel",green(),"▯"),card("AUTONOMIA","aut",Color.WHITE,"⋮"));row(card("TEMPO TOTAL","total",yellow(),"◷"),card("MAX SESSION","max",red(),"◉"));row(card("CLIMA","weather",Color.WHITE,"☁"),card("PISTA MOLHADA","wet",blue(),"◆"));summary();updateUi();}
 void mainGauge(){LinearLayout box=vbox();box.setPadding(dp(16),dp(14),dp(16),dp(14));box.setBackground(box(1,Color.rgb(34,54,58),Color.rgb(3,10,16),18));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView rpmLab=tv("RPM\nx1000",12,txt(),Typeface.BOLD);tach=new Tach(this);clock=tv(now(),13,Color.WHITE,Typeface.BOLD);r.addView(rpmLab,new LinearLayout.LayoutParams(dp(72),dp(70)));r.addView(tach,new LinearLayout.LayoutParams(0,dp(70),1));r.addView(clock,new LinearLayout.LayoutParams(dp(58),dp(70)));box.addView(r);LinearLayout mid=new LinearLayout(this);mid.setGravity(Gravity.CENTER);TextView arrows=tv("≪≪",48,green(),Typeface.BOLD);gear=tv("5\nGEAR",58,Color.WHITE,Typeface.BOLD);speed=tv("287\nkm/h",58,Color.WHITE,Typeface.BOLD);gear.setGravity(Gravity.CENTER);speed.setGravity(Gravity.CENTER);mid.addView(arrows,new LinearLayout.LayoutParams(0,dp(150),1));mid.addView(gear,new LinearLayout.LayoutParams(0,dp(150),1));mid.addView(speed,new LinearLayout.LayoutParams(0,dp(150),1));box.addView(mid);root.addView(box,new LinearLayout.LayoutParams(-1,dp(260)));}
 LinearLayout card(String title,String key,int color,String ico){LinearLayout c=vbox();c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(box(1,Color.rgb(38,54,58),Color.rgb(4,12,18),12));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView lab=tv(title,12,Color.WHITE,Typeface.BOLD);CheckBox cb=new CheckBox(this);cb.setButtonTintList(android.content.res.ColorStateList.valueOf(green()));cb.setChecked(getSharedPreferences(PREF,0).getBoolean("check_"+key,true));final String k=key;cb.setOnClickListener(new View.OnClickListener(){public void onClick(View v){getSharedPreferences(PREF,0).edit().putBoolean("check_"+k,((CheckBox)v).isChecked()).apply();updateUi();}});head.addView(lab,new LinearLayout.LayoutParams(0,-2,1));head.addView(cb,new LinearLayout.LayoutParams(dp(36),dp(36)));TextView icon=tv(ico,20,color,Typeface.BOLD);TextView value=tv("--",24,color,Typeface.BOLD);c.addView(head);c.addView(icon);c.addView(value);checks.put(key,cb);vals.put(key,value);return c;}
 void row(View a,View b){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(92),1);lp.setMargins(0,dp(5),dp(5),dp(5));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(92),1);rp.setMargins(dp(5),dp(5),0,dp(5));r.addView(a,lp);r.addView(b,rp);grid.addView(r);} 
 void summary(){LinearLayout s=vbox();s.setPadding(dp(14),dp(14),dp(14),dp(14));s.setBackground(box(1,Color.rgb(39,63,64),Color.rgb(4,13,17),16));TextView h=tv("▣  RESUMO DA SESSÃO",16,green(),Typeface.BOLD);s.addView(h);LinearLayout r=new LinearLayout(this);r.setPadding(0,dp(14),0,0);TextView logo=tv("🏁",42,Color.WHITE,Typeface.BOLD);LinearLayout l=vbox();brandV=tv("MARCA\nFerrari",14,Color.WHITE,Typeface.NORMAL);carV=tv("CARRO\nF40 '92",14,Color.WHITE,Typeface.NORMAL);carIdV=tv("ID DO CARRO\nferrari_f40_92",13,Color.WHITE,Typeface.NORMAL);l.addView(brandV);l.addView(carV);l.addView(carIdV);LinearLayout rr=vbox();trackV=tv("PISTA\nSardegna - Road Track - A",14,Color.WHITE,Typeface.NORMAL);trackIdV=tv("ID DA PISTA\nsardegna_road_track_a",13,Color.WHITE,Typeface.NORMAL);rr.addView(trackV);rr.addView(trackIdV);r.addView(logo,new LinearLayout.LayoutParams(dp(64),-2));r.addView(l,new LinearLayout.LayoutParams(0,-2,1));r.addView(rr,new LinearLayout.LayoutParams(0,-2,1));s.addView(r);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(12),0,0);root.addView(s,lp);} 
 void bottom(FrameLayout frame){LinearLayout b=new LinearLayout(this);b.setGravity(Gravity.CENTER);b.setBackgroundColor(Color.rgb(3,10,15));String[] names={"◉\nDASHBOARD","◷\nSESSÃO","▧\nHISTÓRICO","⚙\nCONFIG."};for(final String n:names){TextView x=tv(n,12,n.contains("DASH")?green():Color.LTGRAY,Typeface.BOLD);x.setGravity(Gravity.CENTER);b.addView(x,new LinearLayout.LayoutParams(0,dp(72),1));x.setOnClickListener(new View.OnClickListener(){public void onClick(View v){if(n.contains("DASH"))dashboard();else if(n.contains("SESS"))session();else if(n.contains("HIST"))history();else settings();}});}FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-1,dp(78),Gravity.BOTTOM);frame.addView(b,lp);} 
 void session(){root.removeViews(1,root.getChildCount()-1);TextView title=tv("SESSÃO",22,green(),Typeface.BOLD);root.addView(title);Button a=new Button(this);a.setText(active?"FINALIZAR E SALVAR SESSÃO":"INICIAR SESSÃO");a.setOnClickListener(new View.OnClickListener(){public void onClick(View v){if(active)finish();else start();session();}});root.addView(a,new LinearLayout.LayoutParams(-1,dp(58)));root.addView(card("VOLTAS CORRIGIDAS","laps",green(),"◷"));root.addView(card("TEMPO TOTAL","total",yellow(),"◷"));updateUi();}
 void history(){root.removeViews(1,root.getChildCount()-1);TextView t=tv("HISTÓRICO",22,green(),Typeface.BOLD);root.addView(t);try{JSONArray a=new JSONArray(getSharedPreferences(PREF,0).getString("sessions","[]"));TextView body=tv(a.length()==0?"Nenhuma sessão salva":histText(a),15,Color.WHITE,Typeface.NORMAL);body.setPadding(dp(12),dp(12),dp(12),dp(12));body.setBackground(box(1,Color.rgb(35,55,58),Color.rgb(4,13,18),14));root.addView(body);}catch(Exception e){root.addView(tv("Erro ao ler histórico",15,Color.WHITE,0));}}
 String histText(JSONArray a)throws Exception{StringBuilder sb=new StringBuilder();for(int i=a.length()-1;i>=0;i--){JSONObject o=a.getJSONObject(i);sb.append(o.optString("date")).append("\n").append(o.optString("brand")).append(" ").append(o.optString("car")).append("\n").append(o.optString("track")).append("\nMelhor: ").append(o.optString("best")).append("   Max: ").append(o.optString("maxSpeedSession")).append(" km/h\n\n");}return sb.toString();}
 void settings(){final String[] opts={"Bridge URL","Marca","Carro","Pista","Exportar histórico JSON","Importar backup JSON"};new AlertDialog.Builder(this).setTitle("Configurações").setItems(opts,(d,w)->{if(w==0)edit("bridge","Bridge URL",bridge);else if(w==1)edit("brand","Marca",brand);else if(w==2)edit("car","Carro",car);else if(w==3)edit("track","Pista",track);else if(w==4)copy(getSharedPreferences(PREF,0).getString("sessions","[]"));else Toast.makeText(this,"Cole o JSON no próximo build",0).show();}).show();}
 void edit(final String k,String title,String cur){final EditText e=new EditText(this);e.setText(cur);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Salvar",(d,w)->{getSharedPreferences(PREF,0).edit().putString(k,e.getText().toString()).apply();load();updateUi();}).setNegativeButton("Cancelar",null).show();}
 void pollBridge(){new Thread(new Runnable(){public void run(){boolean ok=false;try{String b=http(fix(bridge)+"/api/fields");if(!valid(b))b=http(fix(bridge)+"/api/telemetry");Map<String,String> p=parse(b);if(!p.isEmpty()){for(String k:p.keySet())if(valid(p.get(k))&&!bad(p.get(k)))lastGood.put(k,p.get(k));f.clear();f.putAll(p);lastPacket=System.currentTimeMillis();calc();ok=true;}}catch(Exception e){}final boolean c=ok||System.currentTimeMillis()-lastPacket<3500;h.post(new Runnable(){public void run(){status.setText(c?"● CONECTADO":"● DESCONECTADO");status.setTextColor(c?green():red());updateUi();}});}}).start();}
 String http(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(800);c.setReadTimeout(800);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);r.close();c.disconnect();return s.toString();}
 Map<String,String> parse(String body)throws Exception{Map<String,String> m=new HashMap<>();if(!valid(body))return m;flatten(m,"",new JSONTokener(body.trim()).nextValue());return m;} void flatten(Map<String,String> m,String p,Object o)throws Exception{if(o instanceof JSONObject){JSONObject j=(JSONObject)o;Iterator<String> it=j.keys();while(it.hasNext()){String k=it.next();Object v=j.get(k);String n=p.length()==0?k:p+"."+k;flatten(m,n,v);if(v instanceof JSONObject&&(k.equals("fields")||k.equals("telemetry")||k.equals("car")||k.equals("session")))flatten(m,"",v);}}else m.put(p,String.valueOf(o));}
 String val(String...ks){for(String k:ks){String v=f.get(k);if(valid(v)&&!bad(v))return v;v=lastGood.get(k);if(valid(v)&&!bad(v))return v;}return "--";} float num(String...ks){try{return Float.parseFloat(val(ks).replace("%","").replace(',','.'));}catch(Exception e){return Float.NaN;}} boolean valid(String s){return s!=null&&s.trim().length()>0&&!s.equals("--");} boolean bad(String s){return s.equalsIgnoreCase("null")||s.equalsIgnoreCase("undefined")||s.equalsIgnoreCase("nan");} String fix(String u){return u.startsWith("http")?(u.endsWith("/")?u.substring(0,u.length()-1):u):"http://"+u;}
 void calc(){float sp=num("speed_kmh","speedKmh","speed","velocityKmh","velocidade");if(!Float.isNaN(sp)&&sp>maxSpeed)maxSpeed=sp;String lap=val("lastLap","lastLaptime","last_lap","ultimaVolta");if(active&&valid(lap)&&!lap.equals(lastLapText)){long ms=parseTime(lap);if(ms>0)laps.add(ms);lastLapText=lap;}float fu=num("fuelPercent","combustivelPorcentagem","fuel_percent","fuel");if(!Float.isNaN(fu)){if(Float.isNaN(fuelStart))fuelStart=fu;fuelLast=fu;if(active&&laps.size()>0&&fuelStart-fuelLast>.05f)fuelPerLap=(fuelStart-fuelLast)/laps.size();}}
 void updateUi(){clock.setText(now());float sp=num("speed_kmh","speedKmh","speed","velocityKmh","velocidade");float rp=num("rpm","engine_rpm","currentRpm");tach.rpm=Float.isNaN(rp)?0:rp;tach.invalidate();gear.setText(val("gear","marcha","currentGear")+"\nGEAR");speed.setText(round(sp)+"\nkm/h");set("best",val("bestLap","best_lap","melhorVolta"));set("last",val("lastLap","last_lap","ultimaVolta"));set("total",format(totalMs()));set("max",round(maxSpeed)+" km/h");set("fuel",val("fuelPercent","combustivelPorcentagem","fuel_percent","fuel")+"%");set("aut",autonomy());set("weather",weatherText());set("wet",wetText());set("laps",laps.size()+" voltas");brandV.setText("MARCA\n"+brand);carV.setText("CARRO\n"+car);carIdV.setText("ID DO CARRO\n"+slug(brand+"_"+car));trackV.setText("PISTA\n"+track);trackIdV.setText("ID DA PISTA\n"+slug(track));}
 void set(String k,String v){TextView t=vals.get(k);CheckBox c=checks.get(k);if(t!=null)t.setText(c!=null&&!c.isChecked()?"OFF":(valid(v)?v:"--"));}
 void start(){laps.clear();maxSpeed=0;fuelStart=Float.NaN;fuelLast=Float.NaN;fuelPerLap=Float.NaN;lastLapText="";active=true;getSharedPreferences(PREF,0).edit().putBoolean("active",true).apply();}
 void finish(){active=false;getSharedPreferences(PREF,0).edit().putBoolean("active",false).apply();save();}
 void save(){try{SharedPreferences sp=getSharedPreferences(PREF,0);JSONArray a=new JSONArray(sp.getString("sessions","[]"));JSONObject o=new JSONObject();o.put("date",now());o.put("brand",brand);o.put("car",car);o.put("track",track.length()==0?"Pista não identificada":track);o.put("best",best());o.put("last",val("lastLap","ultimaVolta"));o.put("total",format(totalMs()));o.put("laps",laps.size());o.put("maxSpeedSession",round(maxSpeed));o.put("fuel",val("fuelPercent","combustivelPorcentagem","fuel_percent","fuel"));o.put("telemetry",new JSONObject(f));a.put(o);sp.edit().putString("sessions",a.toString()).apply();}catch(Exception e){}}
 String best(){long b=0;for(Long l:laps)if(b==0||l<b)b=l;return b==0?val("bestLap","melhorVolta"):format(b);} long totalMs(){long t=0;for(Long l:laps)t+=l;return t;} String autonomy(){if(Float.isNaN(fuelLast)||Float.isNaN(fuelPerLap)||fuelPerLap<=0)return "-- voltas";return String.format(Locale.US,"%.1f\nvoltas",fuelLast/fuelPerLap);} String weatherText(){String w=val("weather","clima","condition","rainIntensity");return valid(w)?w:"23°C";} String wetText(){float w=num("trackWetness","track_wetness","surfaceWater","waterOnTrack");if(Float.isNaN(w))return "0%";if(w<=1)w*=100;return Math.round(w)+"%";} String now(){return new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date());} String round(float x){return Float.isNaN(x)?"--":String.valueOf(Math.round(x));} String slug(String s){return s.toLowerCase(Locale.US).replace("'","").replaceAll("[^a-z0-9]+","_").replaceAll("^_+|_+$","");} void copy(String text){((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("GT7",text));Toast.makeText(this,"Copiado",0).show();}
 long parseTime(String s){try{String[] p=s.trim().replace(',','.').split(":");float sec=Float.parseFloat(p[p.length-1]);long min=p.length>=2?Long.parseLong(p[p.length-2]):0;long hr=p.length>=3?Long.parseLong(p[p.length-3]):0;return hr*3600000+min*60000+Math.round(sec*1000);}catch(Exception e){return 0;}} String format(long ms){if(ms<=0)return "--:--.---";long m=ms/60000;ms%=60000;long s=ms/1000,z=ms%1000;return String.format(Locale.US,"%02d:%02d.%03d",m,s,z);} 
 public class Tach extends View{Paint p=new Paint(1);float rpm=0;public Tach(Context c){super(c);}protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();p.setStrokeWidth(dp(3));int n=80;for(int i=0;i<n;i++){float x=dp(4)+i*(w-dp(8))/(float)n;float v=i/(float)n;int col=v<.5?green():(v<.7?Color.rgb(188,255,34):(v<.83?yellow():red()));p.setColor(col);p.setAlpha(i<rpm/10000f*n?255:45);c.drawLine(x,dp(18),x,h-dp(18),p);}p.setAlpha(255);p.setColor(Color.WHITE);p.setStrokeWidth(dp(2));float x=Math.min(w,Math.max(0,(rpm/10000f)*w));c.drawLine(x,0,x,h,p);p.setTextSize(dp(12));p.setTypeface(Typeface.DEFAULT_BOLD);for(int i=0;i<=10;i++){p.setColor(Color.WHITE);c.drawText(String.valueOf(i),i*w/10f+dp(2),h-dp(2),p);}}}
}
