package com.gt7.bridge.mobile;

import android.app.*;
import android.os.*;
import android.view.*;
import android.graphics.*;
import android.content.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.util.*;

public class MainActivity extends Activity{
 static final String VERSION="v1.1";
 static final String PREF="gt7_v11_layout";
 static final String URL_KEY="bridge_url";
 static final String DEFAULT_URL="http://192.168.1.70:8787";
 Handler h=new Handler(Looper.getMainLooper()); Dash dash; Tel tel=new Tel(); String url; boolean run=false;
 Runnable loop=new Runnable(){public void run(){loadTel();h.postDelayed(this,350);}};
 public void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);url=getSharedPreferences(PREF,0).getString(URL_KEY,DEFAULT_URL);dash=new Dash(this);setContentView(dash);start();}
 protected void onResume(){super.onResume();start();} protected void onPause(){super.onPause();stop();}
 void start(){if(!run){run=true;h.post(loop);}} void stop(){run=false;h.removeCallbacks(loop);} 
 void loadTel(){new Thread(()->{try{String s=get(url+"/api/fields");if(s==null||s.trim().length()==0)s=get(url+"/api/telemetry");Tel n=Tel.parse(s,tel);n.status="ONLINE";tel=n;dash.push(n);}catch(Exception e){tel.status="OFFLINE";}runOnUiThread(()->dash.invalidate());}).start();}
 String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(800);c.setReadTimeout(800);BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder sb=new StringBuilder();String l;while((l=br.readLine())!=null)sb.append(l);br.close();c.disconnect();return sb.toString();}

 static class Tel{String status="OFFLINE",gear="N",track="TRACK",last="--",best="--",total="--";int speed=0,rpm=0,thr=0,brk=0,laps=0;float fuel=-1,fuelL=-1,water=Float.NaN,oil=Float.NaN,turbo=Float.NaN,gLat=Float.NaN,gLong=Float.NaN,gVert=Float.NaN,x=Float.NaN,y=Float.NaN,z=Float.NaN;
  static Tel parse(String body,Tel old)throws Exception{String s=body.trim();int a=s.indexOf('{'),b=s.lastIndexOf('}');JSONObject o=new JSONObject(a>=0&&b>a?s.substring(a,b+1):s);if(o.has("fields")&&o.get("fields") instanceof JSONObject)o=o.getJSONObject("fields");if(o.has("telemetry")&&o.get("telemetry") instanceof JSONObject)o=o.getJSONObject("telemetry");Tel t=new Tel();t.speed=i(o,old.speed,"speed_kmh","speed","velocidade");t.rpm=i(o,old.rpm,"rpm","engine_rpm");t.gear=str(o,old.gear,"gear","marcha");if(t.gear.equals("0"))t.gear="N";t.thr=i(o,old.thr,"throttle","throttle_percent");t.brk=i(o,old.brk,"brake","brake_percent");t.track=str(o,old.track,"trackName","track","pista");t.last=str(o,old.last,"lastLap","last_lap_text","ultimaVolta","last_lap");t.best=str(o,old.best,"bestLap","best_lap_text","melhorVolta","best_lap");t.total=str(o,old.total,"totalRaceTime","total_race_time_text","tempoTotal");t.laps=i(o,old.laps,"lap","currentLap","completed_laps","voltasCorrigidas");t.fuel=f(o,old.fuel,"fuelPercent","fuel_percent","combustivelPorcentagem");t.fuelL=f(o,old.fuelL,"fuel","fuelLiters","fuel_liters");t.water=f(o,old.water,"coolantTemp","water_temp","temperaturaAgua");t.oil=f(o,old.oil,"oilTemp","oil_temp");t.turbo=f(o,old.turbo,"turbo","boostPressure","turbo_pressure");t.gLat=f(o,old.gLat,"gForceLat","g_lat","lateralG");t.gLong=f(o,old.gLong,"gForceLong","g_long","longitudinalG");t.gVert=f(o,old.gVert,"gForceVert","g_vertical");if(o.has("position")&&o.get("position") instanceof JSONObject){JSONObject p=o.getJSONObject("position");t.x=f(p,old.x,"x");t.y=f(p,old.y,"y");t.z=f(p,old.z,"z");}else{t.x=f(o,old.x,"x","posX");t.y=f(o,old.y,"y","posY");t.z=f(o,old.z,"z","posZ");}return t;}
  static int i(JSONObject o,int d,String...k){return Math.round(f(o,d,k));} static float f(JSONObject o,float d,String...k){for(String s:k)try{if(o.has(s)&&!o.isNull(s)){float v=Float.parseFloat(String.valueOf(o.get(s)).replace(",","."));if(!Float.isNaN(v)&&!Float.isInfinite(v))return v;}}catch(Exception e){}return d;} static String str(JSONObject o,String d,String...k){for(String s:k)try{if(o.has(s)&&!o.isNull(s)){String v=String.valueOf(o.get(s));if(v.trim().length()>0&&!v.equals("--"))return v;}}catch(Exception e){}return d;}
 }

 class Dash extends View{Paint p=new Paint(1);RectF r=new RectF();SharedPreferences sp=getSharedPreferences(PREF,0);float scale=1,scroll=0,lx,ly,dx,dy;boolean edit=false,snap=true;int sel=-1,mode=0;float[] gx=new float[8],gy=new float[8],gw=new float[8],gh=new float[8],ugx,ugy,ugw,ugh,rgx,rgy,rgw,rgh,clip;boolean[] closed=new boolean[8];float[] lat=new float[80],lng=new float[80],vrt=new float[80];int gi=0;
  String[] title={"GRAFICO DE ACELERACAO","TELEMETRY","LAST LAP","BEST LAP","TOTAL TIME","TIRE STATUS","MAP","SESSIONS"};
  Dash(Activity a){super(a);setBackgroundColor(Color.BLACK);loadLayout();}
  void loadLayout(){float[][] d={{14,292,402,132},{14,432,124,196},{150,432,124,196},{286,432,130,196},{14,640,402,95},{14,747,402,125},{14,884,196,110},{220,884,196,110}};for(int i=0;i<8;i++){gx[i]=sp.getFloat("x"+i,d[i][0]);gy[i]=sp.getFloat("y"+i,d[i][1]);gw[i]=sp.getFloat("w"+i,d[i][2]);gh[i]=sp.getFloat("h"+i,d[i][3]);closed[i]=sp.getBoolean("c"+i,false);}}
  void saveLayout(){SharedPreferences.Editor e=sp.edit();for(int i=0;i<8;i++){e.putFloat("x"+i,gx[i]);e.putFloat("y"+i,gy[i]);e.putFloat("w"+i,gw[i]);e.putFloat("h"+i,gh[i]);e.putBoolean("c"+i,closed[i]);}e.apply();}
  void push(Tel t){lat[gi]=Float.isNaN(t.gLat)?0:lim(t.gLat,-2,2);lng[gi]=Float.isNaN(t.gLong)?0:lim(t.gLong,-2,2);vrt[gi]=Float.isNaN(t.gVert)?0:lim(t.gVert,-2,2);gi=(gi+1)%lat.length;}
  protected void onDraw(Canvas c){scale=getWidth()/430f;c.save();c.scale(scale,scale);draw(c,430,getHeight()/scale);c.restore();}
  void draw(Canvas c,float w,float h){bg(c,w,h);if(edit)grid(c,w,h);top(c,w);speedo(c,215,173,168);c.save();c.translate(0,-scroll);for(int i=0;i<8;i++)drawPanel(c,i);c.restore();nav(c,w,h);if(edit)editBox(c,w,h);} 
  void bg(Canvas c,float w,float h){p.setStyle(Paint.Style.FILL);p.setShader(new LinearGradient(0,0,0,h,Color.rgb(1,5,10),Color.BLACK,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);} 
  void grid(Canvas c,float w,float h){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(.6f);p.setColor(Color.argb(55,90,160,210));for(int x=0;x<w;x+=8)c.drawLine(x,0,x,h,p);for(int y=0;y<h;y+=8)c.drawLine(0,y,w,y,p);} 
  void top(Canvas c,float w){btn(c,10,10,40,34,"R");btn(c,w-72,10,62,34,edit?"SALVAR":"EDIT");txt(c,"GT7 BRIDGE MOBILE "+VERSION,w/2,30,20,Color.WHITE,1,Paint.Align.CENTER);txt(c,tel.status+"  SNAP "+(snap?"ON":"OFF"),w/2,48,9,Color.rgb(30,190,255),1,Paint.Align.CENTER);} 
  void speedo(Canvas c,float cx,float cy,float rad){p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(1,10,18));c.drawCircle(cx,cy,rad,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.argb(160,150,170,190));c.drawCircle(cx,cy,rad-5,p);float start=205,sweep=130;for(int i=0;i<=120;i++){float q=i/120f;float a=(float)Math.toRadians(start+sweep*q);int spd=Math.round(240*q);boolean big=spd%20==0;float r1=rad-(big?24:15),r2=rad-7;p.setStrokeWidth(big?2.2f:1f);p.setColor(spd<80?Color.rgb(20,230,70):spd<150?Color.WHITE:spd<200?Color.rgb(255,155,40):Color.rgb(255,40,45));c.drawLine(cx+(float)Math.cos(a)*r1,cy+(float)Math.sin(a)*r1,cx+(float)Math.cos(a)*r2,cy+(float)Math.sin(a)*r2,p);if(big){txt(c,""+spd,cx+(float)Math.cos(a)*(rad-46),cy+5+(float)Math.sin(a)*(rad-46),11,Color.WHITE,1,Paint.Align.CENTER);}}float q=lim(tel.speed/240f,0,1),a=(float)Math.toRadians(start+sweep*q);p.setStrokeWidth(3);p.setColor(Color.rgb(255,40,45));c.drawLine(cx,cy,cx+(float)Math.cos(a)*(rad-42),cy+(float)Math.sin(a)*(rad-42),p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(2,10,18));c.drawCircle(cx,cy,66,p);txt(c,""+tel.speed,cx,cy+5,50,Color.WHITE,1,Paint.Align.CENTER);txt(c,"km/h",cx,cy+28,9,Color.WHITE,0,Paint.Align.CENTER);round(c,cx-26,cy+44,52,44,8,Color.rgb(4,12,20),Color.argb(190,120,140,160));txt(c,tel.gear,cx,cy+72,24,Color.WHITE,1,Paint.Align.CENTER);txt(c,"MT",cx,cy+87,9,Color.WHITE,0,Paint.Align.CENTER);} 
  void drawPanel(Canvas c,int i){float x=gx[i],y=gy[i],w=gw[i],h=closed[i]?34:gh[i];round(c,x,y,w,h,8,Color.rgb(1,15,26),edit&&i==sel?Color.rgb(0,160,255):Color.argb(95,60,140,210));if(edit&&i==sel)handles(c,x,y,w,h);txt(c,closed[i]?"+":"-",x+15,y+20,14,Color.WHITE,1,Paint.Align.CENTER);txt(c,title[i],x+34,y+22,12,Color.WHITE,1,Paint.Align.LEFT);txt(c,"...",x+w-20,y+21,16,Color.rgb(255,55,80),1,Paint.Align.CENTER);if(!closed[i]){if(i==0)chart(c,x+18,y+34,w-36,h-56);else if(i==5)tires(c,x,y,w,h);else fields(c,i,x,y,w,h);}}
  void chart(Canvas c,float x,float y,float w,float h){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(Color.argb(65,100,150,180));c.drawRect(x,y,w+x,h+y,p);for(int j=0;j<5;j++)c.drawLine(x,y+j*h/4,x+w,y+j*h/4,p);line(c,lat,x,y,w,h,Color.rgb(0,230,50));line(c,lng,x,y,w,h,Color.rgb(255,40,50));line(c,vrt,x,y,w,h,Color.rgb(0,140,255));txt(c,"-10s",x,y+h+13,8,Color.WHITE,0,Paint.Align.LEFT);txt(c,"0s",x+w,y+h+13,8,Color.WHITE,0,Paint.Align.RIGHT);txt(c,"LATERAL     LONGITUDINAL     VERTICAL",x+w/2,y+h+28,8,Color.WHITE,0,Paint.Align.CENTER);} 
  void line(Canvas c,float[] ar,float x,float y,float w,float h,int col){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.5f);p.setColor(col);Path path=new Path();for(int i=0;i<ar.length;i++){int k=(gi+i)%ar.length;float xx=x+i*w/(ar.length-1),yy=y+h/2-ar[k]*h/4;if(i==0)path.moveTo(xx,yy);else path.lineTo(xx,yy);}c.drawPath(path,p);} 
  void fields(Canvas c,int i,float x,float y,float w,float h){String[][] d=data(i);float yy=y+60;for(String[] row:d){txt(c,row[0],x+16,yy,10,Color.rgb(170,210,235),0,Paint.Align.LEFT);txt(c,row[1],x+w-18,yy,12,row[2].equals("g")?Color.rgb(0,230,80):Color.WHITE,0,Paint.Align.RIGHT);yy+=20;}}
  String[][] data(int i){if(i==1)return rows("SPEED",tel.speed+" km/h","RPM",tel.rpm+" rpm","THROTTLE",tel.thr+" %","BRAKE",tel.brk+" %","FUEL",one(tel.fuelL)+" L","OIL TEMP",deg(tel.oil),"WATER TEMP",deg(tel.water));if(i==2)return rows("TIME",tel.last,"LAP",""+tel.laps,"S1","--","S2","--","S3","--","SPD MAX","--");if(i==3)return rows("TIME",tel.best,"LAP","--","S1","--","S2","--","S3","--","SPD MAX","--");if(i==4)return rows("TIME",tel.total,"LAPS",""+tel.laps);if(i==6)return rows("TRACK",tel.track,"X",one(tel.x),"Y",one(tel.y),"Z",one(tel.z));return rows("BOOST",boost(tel.turbo),"RPM",tel.rpm+"");}
  String[][] rows(String...v){String[][] r=new String[v.length/2][3];for(int i=0;i<v.length;i+=2){r[i/2][0]=v[i];r[i/2][1]=v[i+1];r[i/2][2]=v[i+1].contains("1:")?"g":"";}return r;}
  void tires(Canvas c,float x,float y,float w,float h){String[] t={"FL","FR","RL","RR"};for(int i=0;i<4;i++){float bx=x+24+i*(w-48)/4;round(c,bx,y+58,18,42,6,Color.rgb(5,30,12),Color.rgb(90,130,100));p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(0,210,45));c.drawRoundRect(new RectF(bx+4,y+64,bx+14,y+94),4,4,p);txt(c,t[i],bx+32,y+72,10,Color.WHITE,1,Paint.Align.LEFT);txt(c,"-- C",bx+32,y+92,10,Color.WHITE,0,Paint.Align.LEFT);txt(c,"-- bar",bx+32,y+110,10,Color.WHITE,0,Paint.Align.LEFT);}}
  void nav(Canvas c,float w,float h){float y=h-62;round(c,6,y,418,56,10,Color.rgb(2,12,22),Color.argb(70,90,150,190));txt(c,"DASHBOARD",70,y+36,9,Color.rgb(255,55,80),1,Paint.Align.CENTER);txt(c,"MAP",180,y+36,9,Color.WHITE,0,Paint.Align.CENTER);txt(c,"SESSIONS",286,y+36,9,Color.WHITE,0,Paint.Align.CENTER);txt(c,"SETTINGS",380,y+36,9,Color.WHITE,0,Paint.Align.CENTER);} 
  void editBox(Canvas c,float w,float h){float y=h-145;round(c,12,y,406,132,12,Color.rgb(5,16,26),Color.argb(160,120,180,230));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setPathEffect(new DashPathEffect(new float[]{8,6},0));p.setColor(Color.argb(200,130,200,255));c.drawRoundRect(new RectF(12,y,418,y+132),12,12,p);p.setPathEffect(null);txt(c,"MODO EDICAO ATIVO",28,y+28,12,Color.WHITE,1,Paint.Align.LEFT);txt(c,"Grade: 8dp   Snap: "+(snap?"ON":"OFF"),28,y+55,10,Color.WHITE,0,Paint.Align.LEFT);smallBtn(c,28,y+72,70,45,"DESFAZER");smallBtn(c,106,y+72,70,45,"REFAZER");smallBtn(c,184,y+72,70,45,"COPIAR");smallBtn(c,262,y+72,70,45,"COLAR");round(c,340,y+72,64,45,8,Color.rgb(220,40,60),Color.rgb(255,90,110));txt(c,"SALVAR",372,y+99,10,Color.WHITE,1,Paint.Align.CENTER);} 
  void smallBtn(Canvas c,float x,float y,float w,float h,String s){round(c,x,y,w,h,8,Color.rgb(8,20,32),Color.argb(100,130,180,230));txt(c,s,x+w/2,y+27,8,Color.WHITE,0,Paint.Align.CENTER);} 
  void handles(Canvas c,float x,float y,float w,float h){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setPathEffect(new DashPathEffect(new float[]{5,4},0));p.setColor(Color.rgb(0,170,255));c.drawRect(x,y,x+w,y+h,p);p.setPathEffect(null);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(80,190,255));float[][] hs={{x,y},{x+w,y},{x,y+h},{x+w,y+h},{x+w/2,y},{x+w/2,y+h},{x,y+h/2},{x+w,y+h/2}};for(float[] a:hs)c.drawRect(a[0]-4,a[1]-4,a[0]+4,a[1]+4,p);} 
  public boolean onTouchEvent(MotionEvent e){float x=e.getX()/scale,y=e.getY()/scale;if(e.getAction()==MotionEvent.ACTION_DOWN){dx=lx=x;dy=ly=y;sel=find(x,y+scroll);mode=0;if(edit&&sel>=0){float yy=y+scroll;if(x>gx[sel]+gw[sel]-28&&yy>gy[sel]+gh[sel]-28)mode=2;else mode=1;}return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float mx=x-lx,my=y-ly;if(edit&&sel>=0&&mode>0){undoSave();if(mode==1){gx[sel]=snap(gx[sel]+mx);gy[sel]=snap(gy[sel]+my);}else{gw[sel]=snap(lim(gw[sel]+mx,70,410));gh[sel]=snap(lim(gh[sel]+my,40,280));}invalidate();}else{scroll=Math.max(0,scroll-my);invalidate();}lx=x;ly=y;return true;}if(e.getAction()==MotionEvent.ACTION_UP){if(x>358&&y<54){edit=!edit;saveLayout();invalidate();return true;}if(edit&&y>getHeight()/scale-145){editTap(x,y);return true;}int id=find(x,y+scroll);if(id>=0&&Math.abs(x-dx)<8&&Math.abs(y-dy)<8){if(x<gx[id]+32){closed[id]=!closed[id];saveLayout();invalidate();return true;}if(x>gx[id]+gw[id]-52&&y+scroll<gy[id]+38){pick(id);return true;}}saveLayout();return true;}return true;}
  void editTap(float x,float y){float top=getHeight()/scale-145;if(x>28&&x<98&&y>top+72&&y<top+117)undo();else if(x>106&&x<176&&y>top+72&&y<top+117)redo();else if(x>184&&x<254&&y>top+72&&y<top+117)copy();else if(x>262&&x<332&&y>top+72&&y<top+117)paste();else if(x>340&&x<404&&y>top+72&&y<top+117){saveLayout();edit=false;}invalidate();}
  int find(float x,float y){for(int i=7;i>=0;i--){float hh=closed[i]?34:gh[i];if(x>=gx[i]&&x<=gx[i]+gw[i]&&y>=gy[i]&&y<=gy[i]+hh)return i;}return -1;}float snap(float v){return snap?Math.round(v/8f)*8f:v;}void copy(){if(sel>=0){clip=sel;}}void paste(){if(clip>=0&&sel>=0){gx[sel]=gx[(int)clip]+12;gy[sel]=gy[(int)clip]+12;gw[sel]=gw[(int)clip];gh[sel]=gh[(int)clip];closed[sel]=closed[(int)clip];saveLayout();}}void undoSave(){if(ugx==null){ugx=gx.clone();ugy=gy.clone();ugw=gw.clone();ugh=gh.clone();}}void undo(){if(ugx!=null){rgx=gx.clone();rgy=gy.clone();rgw=gw.clone();rgh=gh.clone();gx=ugx;gy=ugy;gw=ugw;gh=ugh;ugx=null;saveLayout();}}void redo(){if(rgx!=null){gx=rgx;gy=rgy;gw=rgw;gh=rgh;rgx=null;saveLayout();}}void pick(int id){String[] ops={"TELEMETRY","LAST LAP","BEST LAP","TOTAL TIME","TIRE STATUS","MAP","BOOST PRESSURE"};new AlertDialog.Builder(MainActivity.this).setTitle("Escolher dados do card").setItems(ops,(d,w)->{title[id]=ops[w];invalidate();}).setNegativeButton("Fechar",null).show();}
  void btn(Canvas c,float x,float y,float w,float h,String t){round(c,x,y,w,h,8,Color.rgb(2,10,18),Color.argb(120,80,150,220));txt(c,t,x+w/2,y+23,10,Color.WHITE,1,Paint.Align.CENTER);}void round(Canvas c,float x,float y,float w,float h,float rad,int fill,int stroke){r.set(x,y,x+w,y+h);p.setStyle(Paint.Style.FILL);p.setColor(fill);c.drawRoundRect(r,rad,rad,p);if(stroke!=Color.TRANSPARENT){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(stroke);c.drawRoundRect(r,rad,rad,p);}}void txt(Canvas c,String s,float x,float y,float sz,int col,int bold,Paint.Align a){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(col);p.setTextSize(sz);p.setTextAlign(a);p.setTypeface(bold==1?Typeface.create(Typeface.SANS_SERIF,Typeface.BOLD):Typeface.create(Typeface.SANS_SERIF,Typeface.NORMAL));c.drawText(s==null?"--":s,x,y,p);}float lim(float v,float a,float b){return Math.max(a,Math.min(b,v));}String one(float v){return Float.isNaN(v)?"--":String.format(Locale.US,"%.1f",v);}String deg(float v){return Float.isNaN(v)?"--":Math.round(v)+" C";}String boost(float v){return Float.isNaN(v)?"--":String.format(Locale.US,"%.2f bar",v);} }
}
